### ISSUE TITLE
Save Contact Information API not updating phone and receive_marketing_info fields in the database

### ISSUE THREAD

**Issue by tueanhtruong** [kirill-zhirnov/boundless-nextjs-ecommerce-template#79]
I'm writing to report an issue with the "Save Contact Information" API [https://docs.boundless-commerce.com/#tag/Checkout/paths/~1orders~1checkout~1contact/post](https://docs.boundless-commerce.com/#tag/Checkout/paths/~1orders~1checkout~1contact/post)
It appears that the API is not correctly updating the "phone" and "receive_marketing_info" fields in the database when a user attempts to save their contact information.

**Comment by kirill-zhirnov** [comment]
Sorry, missed the issue! I will look into it this week.

Thank you!

**Comment by kirill-zhirnov** [comment]
Hi @tueanhtruong 
The issue should be fixed.

Thank you!
