### ISSUE TITLE
Unable to remove images from products

### ISSUE THREAD

**Issue by quangnguyen3499** [kirill-zhirnov/boundless-nextjs-ecommerce-template#84]
I'm unable to remove images from products.
I removed images and saved success but after that, images still there when reloading.

**Comment by kirill-zhirnov** [comment]
Hi @quangnguyen3499 
Thank you for the report. Will look into the issue today.

**Comment by quangnguyen3499** [comment]
Thanks for the quick fix. I'll check it!
