### ISSUE TITLE
Filter products have issue

### ISSUE THREAD

**Issue by sonnt2510** [kirill-zhirnov/boundless-nextjs-ecommerce-template#85]
hi Kirill, i just checked the blank template and tried to filter products by `Type of case` and it wasn't working, here is the URL that I got https://blank.demos.my-boundless.app/category/100?props[undefined][]=609

It also happens with the other templates as well, even with my project that is using your template and already deployed to production a few months ago

**Comment by sonnt2510** [comment]
nevermind i fixed this one on my site, the issue is you've changed the field name `characteristics_id `to `id`, i believe it's in `Filterform.tsx` and `MultipleSelectCharacteristics.tsx`

**Comment by kirill-zhirnov** [comment]
Hi @sonnt2510 ,
I've updated the API - Sorry about that. Our client is up to date - so please upgrade it and typescript highlights changes.

Thank you.
