### ISSUE TITLE
An error occurred while browsing the product

### ISSUE THREAD

**Issue by Serbia580** [kirill-zhirnov/boundless-nextjs-ecommerce-template#86]
Server Error

TypeError: Cannot read properties of undefined (reading 'length')
This error happened while generating the page. Any console logs will be displayed in the terminal window.
Source

components/product/Characteristics.tsx (8:22) @ length

   6 | 
   7 | export default function ProductCharacteristics({characteristics, manufacturer, size}: IProductCharacteristicsProps) {
>  8 | 	if (!characteristics.length) return null;
     | 	                    ^
   9 | 
  10 | 	return (
  11 | 		<div className='product-attrs'>

**Comment by kirill-zhirnov** [comment]
Hi @Serbia580 ,
Thanks for the report!

We will fix the templates in 1-2 days.
